CREATE (it:Department{name: "IT"})
CREATE (hr:Department{name: "HR"})
CREATE (:Employee{name: "Elon Musk", position: "IT Manager"}) -[:MANAGES]-> (it)
CREATE (:Employee{name: "John Smith", position: "HR Manager"}) -[:MANAGES]-> (hr)
CREATE (:Employee{name: "Szymon Kalkowski", position: "Full-Stack Developer"}) -[:WORKS_IN]-> (it)
CREATE (:Employee{name: "Maciej Słupianek", position: "Frontend Developer"}) -[:WORKS_IN]-> (it)
CREATE (:Employee{name: "Piotr Damrych", position: "Backend Developer"}) -[:WORKS_IN]-> (it)
CREATE (:Employee{name: "Mathews Ivy", position: "Recruiter"}) -[:WORKS_IN]-> (hr)
CREATE (:Employee{name: "Adam Snow", position: "Recruiter"}) -[:WORKS_IN]-> (hr)